[package]
name = "fbthrift_socket"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "MIT OR Apache-2.0"
include = ["**/*.rs"]

[lib]
path = "lib.rs"

[dependencies]
fbthrift_framed = { path = "../framed" }
fbthrift_util = { path = "../util" }
fbthrift = { git = "https://github.com/facebook/fbthrift.git", branch = "master" }
anyhow = "1.0"
bytes = { version = "0.5", features = ["serde"] }
futures = { version = "0.3.5", features = ["async-await", "compat"] }
tokio = { version = "=0.2.13", features = ["full"] }
tokio-tower = "0.4"
tokio-util = { version = "0.2", features = ["codec", "udp"] }
tower-service = "0.3"

[target.'cfg(windows)'.dependencies]
uds_windows = "0.1.5"
async-io = "1.3.1"